### ISSUE TITLE
prh を有効にすると特定の条件下でコンパイルができない？

### ISSUE THREAD

**Issue by anchan828** [vvakame/language-review#36]
prh.yml
```yml
version: 1
rules:
  - expected: Cookie
    pattern:  クッキー
```

コンパイルできる　

```re
= test

//emlist{
//}
```
![](https://i.gyazo.com/b5e6c42cc50735548c5047e3799de5f1.png)

終わらない Loding Re:VIEW... 

```re
= test

//emlist{
あ
//}
```

![](https://gyazo.com/6781db3b3bca91b6c3bc859c00879e71.png)
